# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b14cbb9f90f096f019667d706779e3cb69f640561e13a0631b8ccbc92943a311c4afcc20c9daecb1445ffa064d98d57d5af0d9e7207a7b0a6a33ed3ae801397

test:
  secret_key_base: d1d97ddd94586067ad9c4a063e41d01634b5a596d403a07a147e57f779f6d2ef07279325fb50e1694be6bd7fbdb5a425b6b38d069126ca9ce4d1eaa5219e2bba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
